import json
import datetime
import os
import requests

GITHUB_API_URL = "https://api.github.com"

def create_github_issue(title: str, body: str, labels: list = None):
    """Create or update a GitHub Issue in the current repository."""
    repo = os.getenv("GITHUB_REPOSITORY")
    token = os.getenv("GITHUB_TOKEN")

    if not repo or not token:
        print("❌ Missing GITHUB_REPOSITORY or GITHUB_TOKEN environment variables.")
        return

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json"
    }

    # Check if an issue with the same title already exists
    issues_url = f"{GITHUB_API_URL}/repos/{repo}/issues"
    existing = requests.get(issues_url, headers=headers, params={"state": "open", "per_page": 100})
    existing.raise_for_status()

    for issue in existing.json():
        if issue["title"].strip().lower() == title.strip().lower():
            print(f"ℹ️ Issue already exists: {issue['html_url']}")
            return

    payload = {
        "title": title,
        "body": body,
        "labels": labels or ["automation", "vendor-monitor"]
    }

    resp = requests.post(issues_url, headers=headers, json=payload)
    if resp.status_code == 201:
        issue_url = resp.json()["html_url"]
        print(f"✅ Created new GitHub issue: {issue_url}")
    else:
        print(f"❌ Failed to create issue: {resp.status_code} {resp.text}")


def emit_release_event(vendor: str, new_version: str, previous_version: str = None):
    """Emit event and create GitHub issue for new release."""
    timestamp = datetime.datetime.utcnow().isoformat() + "Z"
    title = f"[{vendor.upper()}] New Release Detected: {new_version}"
    body = (
        f"### Vendor: **{vendor}**\n"
        f"- **New Version:** {new_version}\n"
        f"- **Previous Version:** {previous_version or 'N/A'}\n"
        f"- **Detected At:** {timestamp}\n\n"
        f"This issue was automatically generated by the **Vendor Release Monitor** workflow."
    )
    print(f"📢 Creating GitHub issue for new {vendor} release...")
    create_github_issue(title, body, labels=["release", vendor])


def emit_cve_event(vendor: str, stream: str, cve_id: str, severity: str, score: float, status: str):
    """Emit event and create GitHub issue for new CVE detection."""
    timestamp = datetime.datetime.utcnow().isoformat() + "Z"
    title = f"[{vendor.upper()}-{stream}] {cve_id} ({severity})"
    body = (
        f"### CVE Alert for {vendor}/{stream}\n"
        f"- **CVE ID:** {cve_id}\n"
        f"- **Severity:** {severity}\n"
        f"- **CVSS Score:** {score}\n"
        f"- **Status:** {status}\n"
        f"- **Detected At:** {timestamp}\n\n"
        f"This issue was automatically generated by the **Vendor Release Monitor** workflow."
    )
    print(f"📢 Creating GitHub issue for CVE {cve_id}...")
    create_github_issue(title, body, labels=["cve", severity.lower(), vendor])
