import json
import os
import requests
from datetime import datetime
from pathlib import Path

def create_summary_issue():
    """Create or update a weekly GitHub issue summarizing CVEs."""
    repo = os.getenv("GITHUB_REPOSITORY")
    token = os.getenv("GITHUB_TOKEN")

    if not repo or not token:
        print("❌ Missing GITHUB_REPOSITORY or GITHUB_TOKEN")
        return

    report_path = Path("reports/weekly_cve_summary.json")
    if not report_path.exists():
        print("❌ weekly_cve_summary.json not found.")
        return

    data = json.loads(report_path.read_text())

    week = f"{data['week_start']} → {data['week_end']}"
    title = f"📊 Weekly CVE Summary — {week}"
    body = "### Weekly CVE Summary\n\n"
    body += "| Vendor | Critical | High | Medium |\n"
    body += "|---------|-----------|------|--------|\n"

    for vendor, counts in data["vendors"].items():
        crit = counts.get("Critical", 0)
        high = counts.get("High", 0)
        med = counts.get("Medium", 0)
        body += f"| {vendor} | {crit} | {high} | {med} |\n"

    total = data["total"]
    body += f"\n**Total new CVEs detected:** {sum(total.values())}\n\n"
    body += f"📅 Generated at: {data['generated_at']}\n\n"
    body += "This report was automatically generated by the Vendor Release Monitor system."

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json"
    }
    url = f"https://api.github.com/repos/{repo}/issues"

    resp = requests.post(url, headers=headers, json={"title": title, "body": body, "labels": ["weekly-report", "security"]})
    if resp.status_code == 201:
        print(f"✅ Created GitHub issue: {resp.json()['html_url']}")
    else:
        print(f"❌ Failed to create issue: {resp.status_code} {resp.text}")


if __name__ == "__main__":
    create_summary_issue()
